# Generated by Django 4.2 on 2025-05-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subscriber_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriber'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
    ]
